# DeepLens Grafana Datasource Configuration
# Automatically configures Prometheus, Loki, and Jaeger as data sources

apiVersion: 1

datasources:
  # Prometheus - Metrics (Default)
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://deeplens-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"

  # Loki - Logs
  - name: Loki
    type: loki
    access: proxy
    url: http://deeplens-loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

  # Jaeger - Traces
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://deeplens-jaeger:16686
    editable: true
    uid: jaeger
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ["service.name", "service.namespace"]
        mappedTags: [{ key: "service.name", value: "service" }]
        mapTagNamesEnabled: true
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: true
        filterBySpanID: false
      nodeGraph:
        enabled: true
